### ISSUE TITLE
./make_ebook.sh: line 7: ebook-convert: command not found

### ISSUE THREAD

**Issue by ywecur** [rhelsing/worm_scraper#8]
I can't find `ebook-convert` as a package in homebrew. 

How does one install it?

**Comment by rhelsing** [comment]
Hey @ywecur, see: https://github.com/GitbookIO/gitbook/issues/333

**Comment by ywecur** [comment]
I see. Thank you 👍 

We might wan't to add this command after the install calibre line: `ln -s /Applications/calibre.app/Contents/MacOS/ebook-convert /usr/local/bin`

**Comment by ywecur** [comment]
Actually no, my bad. If you install calibre through homebrew the command-line tools are installed by default!
